site_name: 'Scott Zirkel'
site_name_separator: '|'
basics:
  - basic
  - advanced
  - site_verifications
dublin_core:
  - dublin_core
google:
  - google_plus
  - google_cse
social:
  - twitter
  - pinterest
other:
  - app_links
  - mobile
  - apple
  - android
  - favicons
