<x-app-layout>
    <x-slot:title>Empire Strikes Back 3D Sketchcards by</x-slot:title>
    <header>
        <h2 class="font-title text-4xl">Empire Strikes Back 3D</h2>
        <h3 class="mb-4 font-subtitle text-2xl text-gray-800">Topps 2010</h3>
    </header>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-01-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-02-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-03-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-04-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-05-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-06-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-07-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-08-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-09-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-10-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-11-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-12-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-13-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-14-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-15-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-16-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-17-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-18-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-19-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-20-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-21-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-22-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-23-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-24-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-25-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="1000" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-26-scott-zirkel.webp') }}">
        <img alt="Empire Strikes Back 3D sketchcard" loading="lazy" width="465" height="496" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ asset('drawings/sketchcards/empire-strikes-back-3d/empire-strikes-back-27-scott-zirkel.webp') }}">
    </div>
</x-app-layout>
