@inject('storage', 'Illuminate\Support\Facades\Storage')
<x-app-layout>
    <header>
        <h2 class="font-title text-4xl">Indiana Jones Masterpieces</h2>
        <h3 class="mb-4 font-subtitle text-2xl text-tone-800">Topps 2008</h3>
    </header>
    <section class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-01.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-02.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-03.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-04.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-05.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-06.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-07.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-08.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-09.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-10.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-11.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-12.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-13.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-14.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-15.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-16.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-17.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-18.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-19.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-20.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-21.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-22.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="400" height="561" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-23.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="600" height="740" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-24.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="600" height="740" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-25.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="600" height="740" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-28.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="359" height="754" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-29.webp') }}" style="color: transparent;">
        <img alt="Indiana Jones Masterpieces sketchcard" loading="lazy" width="359" height="754" decoding="async" data-nimg="1" class="col-span-1 max-w-full" src="{{ $storage::url('drawings/sketchcards/indiana-jones-masterpieces/indiana-jones-masterpieces-scott-zirkel-30.webp') }}" style="color: transparent;">
    </section>
</x-app-layout>
